### ISSUE TITLE
PHP warning when quoting some posts

### ISSUE THREAD

**Issue by v12mike** [3D-I/qaip#15]
Since upgrading this extension to v1.2.0,  some posts cannot be quoted, giving a phpBB error of: [phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Utils.php on line 76: DOMDocument::loadXML(): EntityRef: expecting ';' in Entity, line: 8

An example of a post which exhibits the problem is:```
 [quote=crapday69 post_id=555947 time=1509899549 user_id=25001]
 give you "[youtube][/youtube]" in the text box. "https://www.youtube.com/watch?time_continue=6&v=[color=#8000FF]lmHUUXweR3I[/color]&ab_channel=GaryGordon". f the [youtube][/youtube] to give you.....  [attachment=0]youtube code.jpg[/attachment]    That should embed the Youtube video.```

You would need to reconstruct this with a real attached image to see the problem.

This was found on a system running phpBB v3.2.7 and php V7.1.32

I have managed to fix the issue and will create a PR.

**Comment by v12mike** [comment]
I have now worked out how to reproduce the bug.

1.  Create a post containing an attachment.
2.  Place [quote] ... [/quote] tags around the attachment tags by editing the original post and submit.
3.  Quote the post using the quote button on the viewtopic form.

**Comment by v12mike** [comment]
I have added another change to m patch which eliminates the error for non-inlined attachments, but they are not showing in the quoted post.  I will have another quick look tomorrow.

**Comment by 3D-I** [comment]
I did it already to no avail, see the PR for further discussion pls
